### PR TITLE
Retry failed callbacks

### LINKED ISSUE #90: Output was not being redirected when the server was overloaded
Last night, before the deadline of the PC assignment I noticed certain submissions were finishing, with status Done, but grade None/100. Clicking them, the output field was empty. This happened when there were ~10 submissions running, and for multiple submissions.
Example of submissions like this:
1516, 1515, 1510, 1505

### PR DESCRIPTION
**Pull request by mgax**
Fixes https://github.com/vmck/acs-interface/issues/90

### CODE REVIEW

**Review by gmuraru — APPROVED** [review]

File: submission/launch.sh [hunk 1]
```diff
@@ -27,4 +27,5 @@ jq -n \
     '{stdout: $out, exit_code: $code,}' > out.json
 
 curl -X POST "${VMCK_CALLBACK_URL}" -d @out.json \
-     --header "Content-Type: application/json"
+     --header "Content-Type: application/json" \
+     --retry 20 --retry-connrefused
```
Comment (gmuraru) [inline submission/launch.sh:31]: Q: should we have a config file for this retry value?

Comment (mgax) [reply submission/launch.sh:31]: Sure, but it would have to get passed from `acs-interface` through `vmck` to this script. I think this script should actually live in `acs-interface` which will make it easier to change things. Let's leave it hardcoded for now.
